/*
AnkhegEmerge()
AnkhegHide()
AddXPObject(AddXPObject(O:Object*,I:XP*) )
*/

///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////

// Broken links

IF // unexpected values
	OR(2)
		GlobalLT("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
		GlobalGT("JO_JOIN_LINK_PLAYER_ID","LOCALS",6)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
END

IF
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",1)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	OR(2)
		!InParty(Player1)
		!Exists(Player1) // TODO: useful ?
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
END

IF
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",2)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	OR(2)
		!InParty(Player2)
		!Exists(Player2)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
END

IF
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",3)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	OR(2)
		!InParty(Player3)
		!Exists(Player3)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
END

IF
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",4)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	OR(2)
		!InParty(Player4)
		!Exists(Player4)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
END

IF
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",5)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	OR(2)
		!InParty(Player5)
		!Exists(Player5)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
END

IF
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",6)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	OR(2)
		!InParty(Player6)
		!Exists(Player6)
THEN
	RESPONSE #100
		SetGlobal("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
END


///////////////////////////////////////////////////////////////////////////////
// Move to linked player

// Familiar without link: the linked player is the first player in the party (which may not be Player1)

// Large range or different area
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",0) // no linked
	!Global("JO_JOIN_LINK_TYPE","LOCALS",-1) // != static mode
	Global("JO_JOIN_CUTSCENE","GLOBAL",0) // no cutscene
	Allegiance(Myself,FAMILIAR)
	!Range(Player1Fill,70)
THEN
	RESPONSE #100
		MoveGlobalObject(Myself,Player1Fill)
END

// Short range
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",0)
	GlobalGT("JO_JOIN_LINK_TYPE","LOCALS",0) // follow with authorised move
	Global("JO_JOIN_CUTSCENE","GLOBAL",0) // no cutscene
	Allegiance(Myself,FAMILIAR)
	!PersonalSpaceDistance(Player1Fill,5) // PersonalSpaceDistance is more reliable than Range at such a low range
	OR(2)
		Global("JO_JOIN_LINK_TYPE","LOCALS",2) // follow close
		!Range(Player1Fill,50)
THEN
	RESPONSE #100
		MoveToObject(Player1Fill)
END


// Linked to Player1

// Large range or different area
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",1)
	!Global("JO_JOIN_LINK_TYPE","LOCALS",-1)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!Range(Player1,70)
THEN
	RESPONSE #100
		MoveGlobalObject(Myself,Player1)
END

// Short range
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",1)
	GlobalGT("JO_JOIN_LINK_TYPE","LOCALS",0)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!PersonalSpaceDistance(Player1,5)
	OR(2)
		Global("JO_JOIN_LINK_TYPE","LOCALS",2)
		!Range(Player1,50)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END


// Linked to Player2

// Large range or different area
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",2)
	!Global("JO_JOIN_LINK_TYPE","LOCALS",-1)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!Range(Player2,70)
THEN
	RESPONSE #100
		MoveGlobalObject(Myself,Player2)
END

// Short range
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",2)
	GlobalGT("JO_JOIN_LINK_TYPE","LOCALS",0)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!PersonalSpaceDistance(Player2,5)
	OR(2)
		Global("JO_JOIN_LINK_TYPE","LOCALS",2)
		!Range(Player2,50)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END


// Linked to Player3

// Large range or different area
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",3)
	!Global("JO_JOIN_LINK_TYPE","LOCALS",-1)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!Range(Player3,70)
THEN
	RESPONSE #100
		MoveGlobalObject(Myself,Player3)
END

// Short range
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",3)
	GlobalGT("JO_JOIN_LINK_TYPE","LOCALS",0)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!PersonalSpaceDistance(Player3,5)
	OR(2)
		Global("JO_JOIN_LINK_TYPE","LOCALS",2)
		!Range(Player3,50)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END


// Linked to Player4

// Large range or different area
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",4)
	!Global("JO_JOIN_LINK_TYPE","LOCALS",-1)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!Range(Player4,70)
THEN
	RESPONSE #100
		MoveGlobalObject(Myself,Player4)
END

// Short range
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",4)
	GlobalGT("JO_JOIN_LINK_TYPE","LOCALS",0)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!PersonalSpaceDistance(Player4,5)
	OR(2)
		Global("JO_JOIN_LINK_TYPE","LOCALS",2)
		!Range(Player4,50)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END


// Linked to Player5

// Large range or different area
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",5)
	!Global("JO_JOIN_LINK_TYPE","LOCALS",-1)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!Range(Player5,70)
THEN
	RESPONSE #100
		MoveGlobalObject(Myself,Player5)
END

// Short range
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",5)
	GlobalGT("JO_JOIN_LINK_TYPE","LOCALS",0)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!PersonalSpaceDistance(Player5,5)
	OR(2)
		Global("JO_JOIN_LINK_TYPE","LOCALS",2)
		!Range(Player5,50)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END


// Linked to Player6

// Large range or different area
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",6)
	!Global("JO_JOIN_LINK_TYPE","LOCALS",-1)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!Range(Player6,70)
THEN
	RESPONSE #100
		MoveGlobalObject(Myself,Player6)
END

// Short range
IF
	ActionListEmpty()
	Global("JO_JOIN_LINK_PLAYER_ID","LOCALS",6)
	GlobalGT("JO_JOIN_LINK_TYPE","LOCALS",0)
	Global("JO_JOIN_CUTSCENE","GLOBAL",0)
	Allegiance(Myself,FAMILIAR)
	!PersonalSpaceDistance(Player6,5)
	OR(2)
		Global("JO_JOIN_LINK_TYPE","LOCALS",2)
		!Range(Player6,50)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

///////////////////////////////////////////////////////////////////////////////

// Reintegrate NPC into party periodically (Every NINE_ROUNDS depending of other NPCs and Triggers above) 

// Could be changed to more or less rounds for players convenience

IF
	ActionListEmpty()
	!ActuallyInCombat()
	Allegiance(Myself,FAMILIAR)
	Global("JO_NOJOIN","GLOBAL",0)
	!Global("JO_JOIN_LINK_TYPE","LOCALS",-1) // != static mode
	NumInPartyLT(6)
	OR(2)
		!GlobalTimerNotExpired("JO_JOIN_JOIN","LOCALS")
		OnCreation()
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("JO_NOJOIN","GLOBAL",1)
		SetGlobal("JO_JOINI","LOCALS",1)
		SetGlobal("JO_JOIN_CLEAR","LOCALS",1) // ScriptAction (All_in_Baf)
		EquipItemEx("JOMINHP1",1)
		SmallWait(1)
		DestroyItem("JOMINHP1")
		SmallWait(1)
		DisplayStringHead(Myself,~Hey.~)
		SetGlobal("JO_JOIN_CUTSCENE","GLOBAL",0) // TODO: security, find a better way to do it
		JoinParty() // Go to All_In_Baf Switch between familiar and party
		SetInterrupt(TRUE)
END

// Maybe something could be done with :

/*
0x0004 Joins(O:Object*)
Returns true if the specified object has joined the party in the last script round. This trigger is only sent to player characters. 

0x0005 Leaves(O:Object*)
Returns true if the specified object has left the party in the last script round. This trigger is only sent to player characters. 
*/


///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////


// Dead but not really  (// Related to AllInBaf set statut when Dead but not really )

IF
	!GlobalGT("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPLT(Myself,5)
THEN
	RESPONSE #10
	DisplayStringHead(Myself,~Carry on without me...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Les carottes sont cuites...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~You're next...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Keep going, I will catch up...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,#4887)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I can't fall... Not now !~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~<CHARNAME> ! For the gods sake...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I don't want to go...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~At last...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I saw it coming... I guess.~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Huh... I can see the darkness !~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Go on without me, my fellow traveler~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Not like this... Not like this !~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Ooooh ! I can see the light !~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~<CHARNAME> ! For the gods sake...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Aaarghhh...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I can't fall... Not now !~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Carry on without me...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,#4888)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~The pointy ears had it right, we're all doomed.~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~My wounds are too grave. I am dead...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,#4887)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~<CHARNAME> ! I curse you !!!~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~You're next...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Carry on without me...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Keep going, I will catch up...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I can't fall... Not now !~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~A fitting death !~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~We're all doomed! Run while you're still able.~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Carry on without me...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I don't want to go...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Carry on without me...~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I saw it coming... I guess.~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I can't fall... Not now !~)
	SmallWait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,#4887)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I will return to finish you off.~)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~Don't you dare leaving me here to rot !~)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	RESPONSE #10
	DisplayStringHead(Myself,~I know your true nature, <CHARNAME>. You're gonna kill all of us...~)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
END

IF
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",1)
	Allegiance(Myself,FAMILIAR)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",2)
	SetSequence(SEQ_DIE)
	Wait(2)
	ReallyForceSpellRES("JOIN648",Myself)
END

///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////

// No more Dead  (// Related to AllInBaf set statut when No more Dead )

IF
	Allegiance(Myself,FAMILIAR)
	HPGT(Myself,4)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",2)
THEN
	RESPONSE #10
	ReallyForceSpellRES("JOIR648",Myself)
	Wait(1)
	SetSequence(SEQ_EMERGE)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",3)
END

IF
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",3)
THEN
	RESPONSE #10
	DisplayStringHead(Myself,~Still alive !~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~Dead ? No more !~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~The sun shines, and I am amazed to see another day.~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~Perhaps I'll survive longer than I had originally thought.~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~You didn't abandon me !~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~It was a... Nice experiment...~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~Well, I guess we have to go on...~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~I may have overreacted.~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~Of "curse"... I didn't mean it.~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	RESPONSE #10
	DisplayStringHead(Myself,~Well, that escalated quickly...~)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
END
/*
IF
	Allegiance(Myself,FAMILIAR)
	HPGT(Myself,4)
	Global("JO_JOIN_SLEEPING_DEADLY","LOCALS",1)
THEN
	RESPONSE #10
	DisplayStringHead(Myself,~Still alive !~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
//	SetSequence(SEQ_AWAKE)
	RESPONSE #10
	DisplayStringHead(Myself,~Still alive !~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
	RESPONSE #10
	DisplayStringHead(Myself,~Still alive !~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
	RESPONSE #10
	DisplayStringHead(Myself,~Still alive !~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
	RESPONSE #10
	DisplayStringHead(Myself,~You didn't abandon me !~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
	RESPONSE #10
	DisplayStringHead(Myself,~It was a... Nice experiment...~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
	RESPONSE #10
	DisplayStringHead(Myself,~Well, I guess we have to go on...~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
	RESPONSE #10
	DisplayStringHead(Myself,~I may have overreacted.~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
	RESPONSE #10
	DisplayStringHead(Myself,~Of curse... I didn't mean it.~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
	RESPONSE #10
	DisplayStringHead(Myself,~Well, that escalated quickly...~)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
END

IF
	Global("JO_JOIN_SLEEPING_DEADLY","LOCALS",2)
THEN
	RESPONSE #10
	ReallyForceSpellRES("JOIR648",Myself)
	Wait(2)
	SetSequence(SEQ_EMERGE)
	Wait(1)
	SetGlobal("JO_JOIN_SLEEPING_DEADLY","LOCALS",0)
END
*/
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////

// Hit


IF
	Delay(3)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPPercentLT(Myself,70)
	!HPPercentLT(Myself,50)
	!HPPercentLT(Myself,30)
	!HPPercentLT(Myself,15)
	!GlobalGT("JO_JOIN_FEELING","LOCALS",0)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~I took a hit.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~Aïe !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~Just a scratch.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~I took a hit.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~Don't make me laugh.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~I took a hit.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~I took a hit.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~I took a hit.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~I took a hit.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~I took a hit.~)
END

IF
	Delay(3)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPPercentLT(Myself,50)
	!HPPercentLT(Myself,30)
	!HPPercentLT(Myself,15)
	!GlobalGT("JO_JOIN_FEELING","LOCALS",1)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I took a heavy blow.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~Ouch !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~A scratch...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I took a heavy blow.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~It tickles when I laugh.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I took a heavy blow.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I took a heavy blow.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I took a heavy blow.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I took a heavy blow.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I took a heavy blow.~)
END

IF
	Delay(3)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPPercentLT(Myself,30)
	!HPPercentLT(Myself,15)
	!GlobalGT("JO_JOIN_FEELING","LOCALS",2)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I really don't feel well.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I really don't feel well.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~All right, it stings a little.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I really don't feel well.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~Dangerous ? I laugh in the face of danger.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I really don't feel well.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I really don't feel well.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I really don't feel well.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I really don't feel well.~)
END

IF
	Delay(3)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPPercentLT(Myself,15)
	!HPPercentLT(Myself,5)
	Global("JO_JOIN_FEELING","LOCALS",3)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I'm at the end of me.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~The end is near.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I can keep going... Can I ?~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I will survive !!!~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I laugh in the face of death...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I'm at the end of me.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I'm at the end of me.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I'm at the end of me.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I'm at the end of me.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",4)
	DisplayStringHead(Myself,~I'm at the end of me.~)
END


// Heal

IF
	Delay(3)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPPercentGT(Myself,29)
	!HPPercentGT(Myself,49)
	!HPPercentGT(Myself,70)
	!HPPercentGT(Myself,99)
	GlobalGT("JO_JOIN_FEELING","LOCALS",3)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~Ha ha ha !!!~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",3)
	DisplayStringHead(Myself,~I will make it, probably...~)
END

IF
	Delay(3)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPPercentGT(Myself,49)
	!HPPercentGT(Myself,79)
	!HPPercentGT(Myself,99)
	GlobalGT("JO_JOIN_FEELING","LOCALS",2)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~A lot of fun.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",2)
	DisplayStringHead(Myself,~I feel better.~)
END

IF
	Delay(3)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPPercentGT(Myself,79)
	!HPPercentGT(Myself,99)
	GlobalGT("JO_JOIN_FEELING","LOCALS",1)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~Want to hear something funny ?~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",1)
	DisplayStringHead(Myself,~All right, I am back !~)
END

IF
	Delay(3)
	Global("JO_JOIN_SLEEPING_DEAD","LOCALS",0)
	Allegiance(Myself,FAMILIAR)
	HPPercentGT(Myself,99)
	!Global("JO_JOIN_FEELING","LOCALS",0)
THEN
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~Joke aside, I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
	RESPONSE #10
	SetGlobal("JO_JOIN_FEELING","LOCALS",0)
	DisplayStringHead(Myself,~I feel Great.~)
END


///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////

